name: Build and upload artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew clean build optimizedJar

    - name: Upload artifacts
      if: ${{ github.event_name == 'release' }}
      env:
        GH_TOKEN: ${{ github.token }}
        TAG_NAME: ${{ github.event.release.tag_name }}
      run: gh release upload "${TAG_NAME}" java-score/build/libs/*-optimized.jar
